;; Marduk Bolaños 2017

(setq inhibit-startup-screen t)

(menu-bar-mode -1)

(package-initialize)
(package-refresh-contents)

(unless (package-installed-p 'ztree)
(package-install 'ztree))


(defvar hfy-html-quote-map
      '(("\"" "&quot;")
	("&" "&amp;")
	("'" "&apos;")
	("<" "&lt;")
	(">" "&gt;")
	(" " "&nbsp;")
	("¡" "&iexcl;")
	("¢" "&cent;")
	("£" "&pound;")
	("¤" "&curren;")
	("¥" "&yen;")
	("¦" "&brvbar;")
	("§" "&sect;")
	("¨" "&uml;")
	("©" "&copy;")
	("ª" "&ordf;")
	("«" "&laquo;")
	("¬" "&not;")
	("­" "&shy;")
	("®" "&reg;")
	("¯" "&macr;")
	("°" "&deg;")
	("±" "&plusmn;")
	("²" "&sup2;")
	("³" "&sup3;")
	("´" "&acute;")
	("µ" "&micro;")
	("¶" "&para;")
	("·" "&middot;")
	("¸" "&cedil;")
	("¹" "&sup1;")
	("º" "&ordm;")
	("»" "&raquo;")
	("¼" "&frac14;")
	("½" "&frac12;")
	("¾" "&frac34;")
	("¿" "&iquest;")
	("À" "&Agrave;")
	("Á" "&Aacute;")
	("Â" "&Acirc;")
	("Ã" "&Atilde;")
	("Ä" "&Auml;")
	("Å" "&Aring;")
	("Æ" "&AElig;")
	("Ç" "&Ccedil;")
	("È" "&Egrave;")
	("É" "&Eacute;")
	("Ê" "&Ecirc;")
	("Ë" "&Euml;")
	("Ì" "&Igrave;")
	("Í" "&Iacute;")
	("Î" "&Icirc;")
	("Ï" "&Iuml;")
	("Ð" "&ETH;")
	("Ñ" "&Ntilde;")
	("Ò" "&Ograve;")
	("Ó" "&Oacute;")
	("Ô" "&Ocirc;")
	("Õ" "&Otilde;")
	("Ö" "&Ouml;")
	("×" "&times;")
	("Ø" "&Oslash;")
	("Ù" "&Ugrave;")
	("Ú" "&Uacute;")
	("Û" "&Ucirc;")
	("Ü" "&Uuml;")
	("Ý" "&Yacute;")
	("Þ" "&THORN;")
	("ß" "&szlig;")
	("à" "&agrave;")
	("á" "&aacute;")
	("â" "&acirc;")
	("ã" "&atilde;")
	("ä" "&auml;")
	("å" "&aring;")
	("æ" "&aelig;")
	("ç" "&ccedil;")
	("è" "&egrave;")
	("é" "&eacute;")
	("ê" "&ecirc;")
	("ë" "&euml;")
	("ì" "&igrave;")
	("í" "&iacute;")
	("î" "&icirc;")
	("ï" "&iuml;")
	("ð" "&eth;")
	("ñ" "&ntilde;")
	("ò" "&ograve;")
	("ó" "&oacute;")
	("ô" "&ocirc;")
	("õ" "&otilde;")
	("ö" "&ouml;")
	("÷" "&divide;")
	("ø" "&oslash;")
	("ù" "&Ugrave;")
	("ú" "&Uacute;")
	("û" "&Ucirc;")
	("ü" "&Uuml;")
	("ý" "&yacute;")
	("þ" "&thorn;")
	("ÿ" "&yuml;")
	("Œ" "&OElig;")
	("œ" "&oelig;")
	("Š" "&Scaron;")
	("š" "&scaron;")
	("Ÿ" "&Yuml;")
	("ƒ" "&fnof;")
	("ˆ" "&circ;")
	("˜" "&tilde;")
	("Α" "&Alpha;")
	("Β" "&Beta;")
	("Γ" "&Gamma;")
	("Δ" "&Delta;")
	("Ε" "&Epsilon;")
	("Ζ" "&Zeta;")
	("Η" "&Eta;")
	("Θ" "&Theta;")
	("Ι" "&Iota;")
	("Κ" "&Kappa;")
	("Λ" "&Lambda;")
	("Μ" "&Mu;")
	("Ν" "&Nu;")
	("Ξ" "&Xi;")
	("Ο" "&Omicron;")
	("Π" "&Pi;")
	("Ρ" "&Rho;")
	("Σ" "&Sigma;")
	("Τ" "&Tau;")
	("Υ" "&Upsilon;")
	("Φ" "&Phi;")
	("Χ" "&Chi;")
	("Ψ" "&Psi;")
	("Ω" "&Omega;")
	("α" "&alpha;")
	("β" "&beta;")
	("γ" "&gamma;")
	("δ" "&delta;")
	("ε" "&epsilon;")
	("ζ" "&zeta;")
	("η" "&eta;")
	("θ" "&theta;")
	("ι" "&iota;")
	("κ" "&kappa;")
	("λ" "&lambda;")
	("μ" "&mu;")
	("ν" "&nu;")
	("ξ" "&xi;")
	("ο" "&omicron;")
	("π" "&pi;")
	("ρ" "&rho;")
	("ς" "&sigmaf;")
	("σ" "&sigma;")
	("τ" "&tau;")
	("υ" "&upsilon;")
	("φ" "&phi;")
	("χ" "&chi;")
	("ψ" "&psi;")
	("ω" "&omega;")
	("ϑ" "&thetasym;")
	("ϒ" "&Upsih;")
	("ϖ" "&piv;")
	(" " "&ensp;")
	(" " "&emsp;")
	(" " "&thinsp;")
	("‌" "&zwnj;")
	("‍" "&zwj;")
	("‎" "&lrm;")
	("‏" "&rlm;")
	("–" "&ndash;")
	("—" "&mdash;")
	("‘" "&lsquo;")
	("’" "&rsquo;")
	("‚" "&sbquo;")
	("“" "&ldquo;")
	("”" "&rdquo;")
	("„" "&bdquo;")
	("†" "&dagger;")
	("‡" "&Dagger;")
	("•" "&bull;")
	("…" "&hellip;")
	("‰" "&permil;")
	("′" "&prime;")
	("″" "&Prime;")
	("‹" "&lsaquo;")
	("›" "&rsaquo;")
	("‾" "&oline;")
	("⁄" "&frasl;")
	("€" "&euro;")
	("ℑ" "&image;")
	("℘" "&weierp;")
	("ℜ" "&real;")
	("™" "&trade;")
	("ℵ" "&alefsym;")
	("←" "&larr;")
	("↑" "&uarr;")
	("→" "&rarr;")
	("↓" "&darr;")
	("↔" "&harr;")
	("↵" "&crarr;")
	("⇐" "&lArr;")
	("⇑" "&UArr;")
	("⇒" "&rArr;")
	("⇓" "&dArr;")
	("⇔" "&hArr;")
	("∀" "&forall;")
	("∂" "&part;")
	("∃" "&exist;")
	("∅" "&empty;")
	("∇" "&nabla;")
	("∈" "&isin;")
	("∉" "&notin;")
	("∋" "&ni;")
	("∏" "&prod;")
	("∑" "&sum;")
	("−" "&minus;")
	("∗" "&lowast;")
	("√" "&radic;")
	("∝" "&prop;")
	("∞" "&infin;")
	("∠" "&ang;")
	("∧" "&and;")
	("∨" "&or;")
	("∩" "&cap;")
	("∪" "&cup;")
	("∫" "&int;")
	("∴" "&there4;")
	("∼" "&sim;")
	("≅" "&cong;")
	("≈" "&asymp;")
	("≠" "&ne;")
	("≡" "&equiv;")
	("≤" "&le;")
	("≥" "&ge;")
	("⊂" "&sub;")
	("⊃" "&sup;")
	("⊄" "&nsub;")
	("⊆" "&sube;")
	("⊇" "&supe;")
	("⊕" "&oplus;")
	("⊗" "&otimes;")
	("⊥" "&perp;")
	("⋅" "&sdot;")
	("⌈" "&lceil;")
	("⌉" "&rceil;")
	("⌊" "&lfloor;")
	("⌋" "&rfloor;")
	("〈" "&lang;")
	("〉" "&rang;")
	("◊" "&loz;")
	("♠" "&spades;")
	("♣" "&clubs;")
	("♥" "&hearts;")
	("♦" "&diams;")))


(defun quoteme-chars (result chars-list)
  (interactive)
  (if (> (length chars-list) 0)
      (quoteme-chars (concat result (caar chars-list)) (cdr chars-list))
    result))


(defvar hfy-html-quote-regex (concat "\\([" (quoteme-chars "" hfy-html-quote-map) "]\\)" ))


(defun dir-tree ()
  "Show directory tree"
  (interactive)
  (ztree-dir "~"))


(defun tree-to-html ()
  "Export directory tree"
  (interactive)
  (htmlfontify-buffer)
  (write-file "tree.html")
  (browse-url-of-file "tree.html")
  )


;; Override default toolbar
(setq tool-bar-map (make-sparse-keymap))

(tool-bar-add-item "home" 'dir-tree
		   'home
		   :help   "Go home")



(tool-bar-add-item "open" 'ztree-toggle-expand-subtree
		   'dir-open
		   :help   "Expand subtree")



(tool-bar-add-item "left-arrow" 'ztree-dir-widen-to-parent
		   'widen-to-parent
		   :help   "Widen to parent directory")


(tool-bar-add-item "right-arrow" 'ztree-dir-narrow-to-dir
		   'narrow-to-dir
		   :help   "Narrow to selected directory")


(tool-bar-add-item "next-node" 'tree-to-html
		   'tree-to-html
		   :help   "Export to HTML")


(dir-tree)


